import os
from pathlib import Path
from typing import Any, Dict

DOCKERFILE_CPU = """FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python", "runner.py"]
"""

DOCKERFILE_CUDA = """FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-pip \\
    python3-dev \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python3", "runner.py"]
"""

RUNNER_TEMPLATE = """import torch
import os
from pathlib import Path

# Config generated by SysAware ML Optimizer
CONFIG = {config_json}

def load_model(path):
    print(f"Loading model from {{path}}...")
    # Using weights_only=True for security where possible
    model = torch.load(path, map_location="cpu")
    
    mode = CONFIG.get("mode", "none")
    device = CONFIG.get("metadata", {{}}).get("device", "cpu")
    
    if mode == "int8":
        print("Applying INT8 dynamic quantization...")
        model = torch.quantization.quantize_dynamic(
            model, {{torch.nn.Linear, torch.nn.Conv1d, torch.nn.Conv2d}}, dtype=torch.qint8
        )
    
    if device in ["cuda", "mps"]:
        print(f"Moving model to {{device}} and converting to FP16...")
        model = model.to(device).half()
        
    return model

if __name__ == "__main__":
    model_path = os.getenv("MODEL_PATH", "{model_name}")
    model = load_model(model_path)
    print("Model ready for inference.")
    # Add your inference logic here
"""

SYSTEMD_TEMPLATE = """[Unit]
Description=SysAware Optimized ML Model Service ({model_name})
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory={work_dir}
ExecStart=/usr/bin/python3 {work_dir}/runner.py
Restart=always
Environment=MODEL_PATH={model_path}

[Install]
WantedBy=multi-user.target
"""

def export_deployment_artifacts(report: Dict[str, Any], output_dir: str = "deploy"):
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    best_config = report["best_config"]
    model_path = Path(report["model_path"])
    model_name = model_path.name
    
    # 1. runner.py
    import json
    runner_content = RUNNER_TEMPLATE.format(
        config_json=json.dumps(best_config, indent=4),
        model_name=model_name
    )
    (out_path / "runner.py").write_text(runner_content)
    
    # 2. Dockerfile
    device = best_config.get("metadata", {}).get("device", "cpu")
    if device == "cuda":
        docker_content = DOCKERFILE_CUDA
    else:
        docker_content = DOCKERFILE_CPU
    (out_path / "Dockerfile").write_text(docker_content)
    
    # 3. requirements.txt
    reqs = ["torch", "psutil"] # Basic requirements
    (out_path / "requirements.txt").write_text("\\n".join(reqs))
    
    # 4. systemd service
    systemd_content = SYSTEMD_TEMPLATE.format(
        model_name=model_name,
        work_dir=str(out_path.absolute()),
        model_path=str(model_path.absolute())
    )
    (out_path / "sysaware-model.service").write_text(systemd_content)
    
    return str(out_path.absolute())
