import os
import json
from pathlib import Path
from typing import Any, Dict, Optional

DOCKERFILE_CPU = """FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Add non-root user for security compliance
RUN groupadd -g 1000 sysaware && useradd -u 1000 -g sysaware -m -s /bin/bash sysaware

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Adjust permissions and run as non-root
RUN chown -R sysaware:sysaware /app
USER sysaware

# Senior ML Engineer Best Practice: Health Check
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1

ENTRYPOINT ["uvicorn", "runner:app", "--host", "127.0.0.1", "--port", "8000"]
"""

DOCKERFILE_CUDA = """FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-pip \\
    python3-dev \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Add non-root user for security compliance
RUN groupadd -g 1000 sysaware && useradd -u 1000 -g sysaware -m -s /bin/bash sysaware

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

# Adjust permissions and run as non-root
RUN chown -R sysaware:sysaware /app
USER sysaware

# Senior ML Engineer Best Practice: Health Check
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1

ENTRYPOINT ["uvicorn", "runner:app", "--host", "127.0.0.1", "--port", "8000"]
"""

RUNNER_TEMPLATE = """from fastapi import FastAPI, HTTPException, Request
import torch
import os
import time
from pathlib import Path
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(title="SysAware Optimized Model Server")

# Config generated by SysAware ML Optimizer
CONFIG = {config_json}
MODEL = None

class InferenceRequest(BaseModel):
    data: List[float]
    shape: Optional[List[int]] = None

class InferenceResponse(BaseModel):
    prediction: List[float]
    latency_ms: float

# API Key / Bearer Authentication Middleware
SYSAWARE_API_KEY = os.getenv("SYSAWARE_API_KEY")
if not SYSAWARE_API_KEY:
    import secrets
    SYSAWARE_API_KEY = "sysaware_runner_" + secrets.token_hex(16)
    print("\\n" + "!" * 60)
    print("WARNING: No SYSAWARE_API_KEY was provided.")
    print("Generated a secure random API key for this runner:")
    print("  " + SYSAWARE_API_KEY)
    print("Please set SYSAWARE_API_KEY in your environment to use a persistent key.")
    print("!" * 60 + "\\n")

@app.middleware("http")
async def verify_auth(request: Request, call_next):
    if request.url.path == "/health":
        return await call_next(request)
    provided_key = request.headers.get("X-API-Key")
    if not provided_key:
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            provided_key = auth_header[7:]
    if provided_key != SYSAWARE_API_KEY:
        from fastapi.responses import JSONResponse
        return JSONResponse(
            status_code=401,
            content={{"detail": "Unauthorized: Invalid or missing API key."}}
        )
    return await call_next(request)

@app.on_event("startup")
def load_model():
    global MODEL
    path = os.getenv("MODEL_PATH", "{model_name}")
    print(f"Loading model from {{path}}...")
    
    # Senior ML Engineer Best Practice: Use TorchScript/ONNX where possible
    if path.endswith(".pt"):
        # Using weights_only=True for security where possible
        MODEL = torch.load(path, map_location="cpu", weights_only=True)
    elif path.endswith(".ot") or path.endswith(".ts"):
        MODEL = torch.jit.load(path, map_location="cpu")
    else:
        # Fallback for raw weights
        MODEL = torch.load(path, map_location="cpu")
    
    mode = CONFIG.get("mode", "none")
    device = CONFIG.get("metadata", {{}}).get("device", "cpu")
    
    if mode == "int8" and hasattr(torch.quantization, 'quantize_dynamic'):
        print("Applying INT8 dynamic quantization...")
        MODEL = torch.quantization.quantize_dynamic(
            MODEL, {{torch.nn.Linear, torch.nn.Conv1d}}, dtype=torch.qint8
        )
    
    if device in ["cuda", "mps"] and torch.cuda.is_available():
        print(f"Moving model to {{device}} and converting to FP16...")
        MODEL = MODEL.to(device).half()
        
    MODEL.eval()
    print("Model ready for inference.")

@app.get("/health")
def health():
    return {{"status": "healthy", "model_loaded": MODEL is not None}}

@app.post("/predict", response_model=InferenceResponse)
async def predict(request: InferenceRequest):
    if MODEL is None:
        raise HTTPException(status_code=503, detail="Model not loaded")
    
    start_time = time.time()
    try:
        with torch.no_grad():
            input_tensor = torch.tensor(request.data)
            if request.shape:
                input_tensor = input_tensor.view(*request.shape)
            
            output = MODEL(input_tensor)
            prediction = output.tolist()
    except Exception as e:
        raise HTTPException(status_code=500, detail="Inference processing failed")
    
    latency = (time.time() - start_time) * 1000
    return InferenceResponse(prediction=prediction, latency_ms=latency)

if __name__ == "__main__":
    import uvicorn
    bind_host = os.getenv("SYSAWARE_BIND", "127.0.0.1")
    uvicorn.run(app, host=bind_host, port=8000)
"""

SYSTEMD_TEMPLATE = """[Unit]
Description=SysAware Optimized ML Model Service ({model_name})
After=network.target

[Service]
Type=simple
User=sysaware
WorkingDirectory={work_dir}
Environment=MODEL_PATH={model_path}
ExecStart=/usr/bin/python3 {work_dir}/runner.py
Restart=always

[Install]
WantedBy=multi-user.target
"""

def export_to_torchscript(model: Any, example_input: Any, path: str):
    """Senior ML Engineer Practice: Export to TorchScript for production portability."""
    try:
        import torch
        model.eval()
        traced_model = torch.jit.trace(model, example_input)
        traced_model.save(path)
        return True
    except Exception as e:
        print(f"TorchScript export failed: {e}")
        return False

def export_deployment_artifacts(report: Dict[str, Any], output_dir: str = "deploy", export_format: str = "pytorch"):
    """
    Enhanced exporter following Senior ML Engineer best practices:
    - Standardized export (TorchScript)
    - Containerization with Health Checks
    - FastAPI inference server
    """
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    best_config = report["best_config"]
    model_path = Path(report["model_path"])
    
    # 1. Model Saving/Export
    model_filename = f"model.{'ts' if export_format == 'torchscript' else 'pt'}"
    target_model_path = out_path / model_filename
    
    import torch
    # In a real scenario, we would load the model object from memory. 
    # Here we assume it might be a file path in the report for simplicity.
    if "model_obj" in report:
        model = report["model_obj"]
        if export_format == "torchscript":
            dummy_input = torch.randn(1, 10) # Placeholder input
            export_to_torchscript(model, dummy_input, str(target_model_path))
        else:
            torch.save(model, str(target_model_path))
    else:
        # Just copy the existing model file if no object is provided
        import shutil
        shutil.copy(str(model_path), str(target_model_path))

    # 2. Generate requirements.txt
    reqs = ["torch", "fastapi", "uvicorn", "pydantic", "psutil"]
    (out_path / "requirements.txt").write_text("\n".join(reqs))
    
    # 3. Generate runner.py (FastAPI)
    runner_content = RUNNER_TEMPLATE.format(
        config_json=json.dumps(best_config, indent=4),
        model_name=model_filename
    )
    (out_path / "runner.py").write_text(runner_content)
    
    # 4. Generate Dockerfile
    device = best_config.get("metadata", {}).get("device", "cpu")
    docker_content = DOCKERFILE_CUDA if device == "cuda" else DOCKERFILE_CPU
    (out_path / "Dockerfile").write_text(docker_content)
    
    # 5. Generate systemd service
    systemd_content = SYSTEMD_TEMPLATE.format(
        model_name=model_filename,
        work_dir=str(out_path.absolute()),
        model_path=str(target_model_path.absolute())
    )
    (out_path / "sysaware-model.service").write_text(systemd_content)
    
    return str(out_path.absolute())
